In [1]:
import pandas as pd

načítanie dát

In [16]:
df = pd.read_csv("contract_criteria_export.csv")

odstránenie cenových kritérií

In [23]:
pattern = r'\bcena\b|\bcien\b|\bceny\b|\bnáklad'

#Filtrovanie riadkov, ktoré Neobsahujú tieto výrazy
df_necenove = df[~df['criterion'].str.contains(pattern, case=False, na=False)]

In [24]:
df_necenove

,contract_id,criterion,description,label
3,3254340,Lehota realizácie prác,Projekt rieši stavebné úpravy pre zníženie ene...,Stavebné práce
6,3254631,Počet kalendárnych dní realizácie stavebnych prác,Miestne kultúrne stredisko je samostatne stoja...,Stavebné práce
9,3254635,Lehota výstavby v dňoch,Predmetom zákazky je komplexná rekonštrukcia b...,Stavebné práce na stavbe budov
14,3254875,Lehota realizácie prác v týždňoch,Zámerom verejného obstarávateľa sú stavebné úp...,Stavebné práce
16,3254905,Najvyšší počet pevných sedadiel,Predmetom zákazky je dodávka osobných klimatiz...,Železničné osobné vozne
...,...,...,...,...
149090,3343438,Ekonomicky najvýhodnejšia ponuka z hľadiska,Dodávka oceľového potrubia s vonkajším priemer...,Diaľkové plynovody
149091,3343439,Ekonomicky najvýhodnejšia ponuka z hľadiska,Dodávka oceľového potrubia s vonkajším priemer...,Diaľkové plynovody
149154,3343912,Ekonomicky najvýhodnejšia ponuka z hľadiska,Tento projekt rieši zmenu stavby pred dokončen...,Stavebné práce na stavbe budov materských škôl
154371,3538374,Ekonomicky najvýhodnejšia ponuka z hľadiska,"Predmetom zákazky je návrh, vybudovanie a prev...","Služby informačných technológií: konzultácie, ..."
154842,3538919,Ekonomicky najvýhodnejšia ponuka z hľadiska,Jedná sa o dodávku 2 ks nového nízkopodlažného...,Trolejbusy

uloženie necenových kritérií

In [25]:
df_necenove.to_csv("contract_criteria_necenove.csv", index=False, encoding="utf-8")

použitie chatGPT na splitnutie viacerých kritérií v jednom zázname

In [41]:
df_Split = pd.read_csv("contract_criteria_clean_split.csv")

In [42]:
df_Split

,contract_id,criterion,description,label
0,3254340.0,Lehota realizácie prác,Projekt rieši stavebné úpravy pre zníženie ene...,Stavebné práce
1,3254631.0,Počet kalendárnych dní realizácie stavebnych prác,Miestne kultúrne stredisko je samostatne stoja...,Stavebné práce
2,3254635.0,Lehota výstavby v dňoch,Predmetom zákazky je komplexná rekonštrukcia b...,Stavebné práce na stavbe budov
3,3254875.0,Lehota realizácie prác v týždňoch,Zámerom verejného obstarávateľa sú stavebné úp...,Stavebné práce
4,3254905.0,Najvyšší počet pevných sedadiel,Predmetom zákazky je dodávka osobných klimatiz...,Železničné osobné vozne
...,...,...,...,...
2546,3343438.0,Ekonomicky najvýhodnejšia ponuka z hľadiska,Dodávka oceľového potrubia s vonkajším priemer...,Diaľkové plynovody
2547,3343439.0,Ekonomicky najvýhodnejšia ponuka z hľadiska,Dodávka oceľového potrubia s vonkajším priemer...,Diaľkové plynovody
2548,3343912.0,Ekonomicky najvýhodnejšia ponuka z hľadiska,Tento projekt rieši zmenu stavby pred dokončen...,Stavebné práce na stavbe budov materských škôl
2549,3538374.0,Ekonomicky najvýhodnejšia ponuka z hľadiska,"Predmetom zákazky je návrh, vybudovanie a prev...","Služby informačných technológií: konzultácie, ..."
2550,3538919.0,Ekonomicky najvýhodnejšia ponuka z hľadiska,Jedná sa o dodávku 2 ks nového nízkopodlažného...,Trolejbusy