Inštalácia pyreadstat

In [1]:
!pip install pyreadstat

Collecting pyreadstat
  Obtaining dependency information for pyreadstat from https://files.pythonhosted.org/packages/c5/27/a919731092492263da67161466c4971b3a22bbb38bec1a714849d71c90af/pyreadstat-1.2.9-cp311-cp311-win_amd64.whl.metadata
  Downloading pyreadstat-1.2.9-cp311-cp311-win_amd64.whl.metadata (1.3 kB)
Requirement already satisfied: pandas>=1.2.0 in c:\users\marek\appdata\local\programs\python\python311\lib\site-packages (from pyreadstat) (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\marek\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\marek\appdata\roaming\python\python311\site-packages (from pandas>=1.2.0->pyreadstat) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\marek\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\marek\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\marek\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadstat) (1.16.0)
Downloading pyreadstat-1.2.9-cp311-cp311-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
    --------------------------------------- 0.0/2.4 MB 393.8 kB/s eta 0:00:06
   - -------------------------------------- 0.1/2.4 MB 819.2 kB/s eta 0:00:03
   ---- ----------------------------------- 0.3/2.4 MB 1.6 MB/s eta 0:00:02
   ------ --------------------------------- 0.4/2.4 MB 2.0 MB/s eta 0:00:01
   ----------- ---------------------------- 0.7/2.4 MB 2.6 MB/s eta 0:00:01
   -------------- ------------------------- 0.8/2.4 MB 2.8 MB/s eta 0:00:01
   --------------- ------------------------ 0.9/2.4 MB 2.5 MB/s eta 0:00:01
   ----------------------- ---------------- 1.4/2.4 MB 3.6 MB/s eta 0:00:01
   --------------------------- ------------ 1.7/2.4 MB 3.7 MB/s eta 0:00:01
   ------------------------------- -------- 1.9/2.4 MB 3.9 MB/s eta 0:00:01
   ------------------------------------ --- 2.2/2.4 MB 4.0 MB/s eta 0:00:01
   -------------------------------------- - 2.3/2.4 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 3.9 MB/s eta 0:00:00
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.2.9

[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Načítanie dát

In [27]:
import pyreadstat

df, meta = pyreadstat.read_sav("contract_eval_CPV_HI.sav")

In [28]:
df.head(5)

,contract_evaluation_criterion_id,contract_id,evaluation_criterion_id,weight,criterion,identifier,start_date,title,part_title,description,part,contract_cpv_code_id,cpv_code_id,cpv,label,cpv2,cpv3,cpv4
0,1198942.0,3254290,7.0,0.0,Kritéria nákladov,425159.0,2020-03-05,Udržiavacie stavebné práce,,Predmetom zákazky Udržiavacie stavebné práce j...,0,2463616.0,6346.0,45000000-7,Stavebné práce,45,450,4500
1,1198943.0,3254290,3415.0,100.0,Zľava vyjadrená v percentách (%) z ceny predme...,425159.0,2020-03-05,Udržiavacie stavebné práce,,Predmetom zákazky Udržiavacie stavebné práce j...,0,2463616.0,6346.0,45000000-7,Stavebné práce,45,450,4500
2,1198977.0,3254340,7.0,0.0,Kritéria nákladov,412105.0,2017-12-22,Zníženie energetickej náročnosti Obecnej budov...,,Projekt rieši stavebné úpravy pre zníženie ene...,0,2463686.0,6346.0,45000000-7,Stavebné práce,45,450,4500
3,1198979.0,3254340,2685.0,20.0,Lehota realizácie prác,412105.0,2017-12-22,Zníženie energetickej náročnosti Obecnej budov...,,Projekt rieši stavebné úpravy pre zníženie ene...,0,2463686.0,6346.0,45000000-7,Stavebné práce,45,450,4500
4,1198978.0,3254340,2665.0,80.0,Cena stavebných prác,412105.0,2017-12-22,Zníženie energetickej náročnosti Obecnej budov...,,Projekt rieši stavebné úpravy pre zníženie ene...,0,2463686.0,6346.0,45000000-7,Stavebné práce,45,450,4500

Výber požadovaných atribútov a uloženie do CSV

In [29]:
# Vyber požadované stĺpce
selected_columns = ['contract_id', 'criterion', 'description', 'label']
df_selected = df[selected_columns]

# Ulož do nového CSV súboru
df_selected.to_csv("contract_criteria_export.csv", index=False, encoding="utf-8")

In [30]:
df_selected.head(5)

,contract_id,criterion,description,label
0,3254290,Kritéria nákladov,Predmetom zákazky Udržiavacie stavebné práce j...,Stavebné práce
1,3254290,Zľava vyjadrená v percentách (%) z ceny predme...,Predmetom zákazky Udržiavacie stavebné práce j...,Stavebné práce
2,3254340,Kritéria nákladov,Projekt rieši stavebné úpravy pre zníženie ene...,Stavebné práce
3,3254340,Lehota realizácie prác,Projekt rieši stavebné úpravy pre zníženie ene...,Stavebné práce
4,3254340,Cena stavebných prác,Projekt rieši stavebné úpravy pre zníženie ene...,Stavebné práce